[versions]
agp = "8.2.2"

junit = "4.13.2"
extJunit = "1.1.5"
espresso = "3.5.1"

appcompat = "1.7.0"
material = "1.11.0"
activity = "1.8.2"
constraintlayout = "2.1.4"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }

ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extJunit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
